logging:
  level:
    ROOT: INFO
    com.redhat.parodos: DEBUG
spring:
  ldap:
    embedded:
      ldif: classpath:test-server.ldif
      base-dn: dc=springframework,dc=org
      port: 8389
    connection:
      userDNPatterns: "${LDAP_USERDNPATTERNS:uid={0},ou=people}"
      groupSearchBase: "${LDAP_GROUP_SEARCH_BASE:ou=groups}"
      url: "${LDAP_URL:ldap://ldap:389/dc=parodos,dc=dev}"
      passwordAttribute: "${LDAP_PASSWORD_ATTRIBUTE:userPassword}"
      managerDN: "${LDAP_MANAGER_DN:cn=admin,dc=parodos,dc=dev}"
      managerPassword: "${LDAP_MANAGER_PASSWORD:admin}"
  lifecycle:
    timeout-per-shutdown-phase: "25s"

notification:
  url: "${NOTIFICATION_SERVER_URL:http://localhost:8081}"
  auth:
    basic:
      user: test
      password: test

workflows:
  mta:
    url: "${MTA_URL:https://mta-openshift-mta.apps.parodos-dev.projects.ecosystem.sysdeseng.com}"
  m2k:
    url: "${M2K_URL:http://localhost:8081/api/v1}"
    public_url: "${M2K_PUBLIC_URL:}"
